{{- if .Values.s3.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "seaweedfs.name" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs-s3
  annotations:
    {{ omit .Values.s3.ingress.annotations "kubernetes.io/ingress.class" | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.s3.ingress.className | quote }}
  tls:
    {{ .Values.s3.ingress.tls | default list | toYaml | nindent 6}}
  rules:
    - host: {{ .Values.s3.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "seaweedfs.name" . }}-s3
                port:
                  name: swfs-s3
                  # number: {{ .Values.s3.port }}
{{- else }}
              serviceName: {{ template "seaweedfs.name" . }}-s3
              servicePort: {{ .Values.s3.port }}
{{- end }}
{{- end }}
