version: '2'

services:
  master0:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "-v=4 master -volumeSizeLimitMB 100 -ip=master0 -port=9333 -peers=master1:9334,master2:9335 -mdir=/data"
    volumes:
      - ./master/0:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
  master1:
    image: chrislusf/seaweedfs:local
    ports:
      - 9334:9334
      - 19334:19334
    command: "-v=4 master -volumeSizeLimitMB 100 -ip=master1 -port=9334 -peers=master0:9333,master2:9335 -mdir=/data"
    volumes:
      - ./master/1:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
  master2:
    image: chrislusf/seaweedfs:local
    ports:
      - 9335:9335
      - 19335:19335
    command: "-v=4 master -volumeSizeLimitMB 100 -ip=master2 -port=9335 -peers=master0:9333,master1:9334 -mdir=/data"
    volumes:
      - ./master/2:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1