name: "Ceph S3 tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/s3tests
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    working-directory: docker

jobs:
  s3tests:
    name: Ceph S3 tests
    runs-on: ubuntu-22.04
    container:
      image: docker.io/kmlebedev/ceph-s3-tests:0.0.2
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
        id: go

      - name: Start SeaweedFS
        run: |
          cd /__w/seaweedfs/seaweedfs/weed
          go install -buildvcs=false
          set -x
          nohup weed -v 1 server -filer -s3 -ip.bind 0.0.0.0 \
            -master.raftHashicorp -master.electionTimeout 1s -master.volumeSizeLimitMB=1024 \
            -volume.max=0 -volume.preStopSeconds=1 -s3.port=8000 -metricsPort=9324 \
            -s3.allowEmptyFolder=false -s3.allowDeleteBucketNotEmpty=true -s3.config=../docker/compose/s3.json &
          sleep 5
      - name: Run Ceph S3 tests
        timeout-minutes: 15
        env:
          S3TEST_CONF: /__w/seaweedfs/seaweedfs/docker/compose/s3tests.conf
        run: |
          cd /s3-tests
          tox -- \
          s3tests_boto3/functional/test_s3.py::test_bucket_list_empty \
          s3tests_boto3/functional/test_s3.py::test_bucket_list_distinct \
          s3tests_boto3/functional/test_s3.py::test_bucket_list_many \
          s3tests_boto3/functional/test_s3.py::test_bucket_listv2_many \
          s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix \
          s3tests_boto3/functional/test_s3.py::test_copy_object_ifnonematch_failed
